#!/usr/bin/env python3
"""Audit RV3D paper-facing experiment readiness.

This is a lightweight repository hygiene check.  It does not edit source files
or delete artifacts.  It verifies that the paper-facing result chain is present,
checks important CSV rollups for readable values, flags possible overclaims in
documentation, and points out likely temporary files.
"""

from __future__ import annotations

import argparse
import csv
import re
import subprocess
from pathlib import Path


CHECKS: list[dict[str, str]] = []


def add_check(section: str, item: str, status: str, detail: str) -> None:
    CHECKS.append(
        {
            "section": section,
            "item": item,
            "status": status,
            "detail": detail,
        }
    )


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def write_csv(path: Path, rows: list[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = ["section", "item", "status", "detail"]
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    print(path)


def write_markdown(path: Path, rows: list[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    counts: dict[str, int] = {}
    for row in rows:
        counts[row["status"]] = counts.get(row["status"], 0) + 1

    lines = [
        "# Paper Readiness Audit",
        "",
        "This file is generated by `audit_paper_readiness.py`.",
        "",
        "## Summary",
        "",
    ]
    for status in ("FAIL", "WARN", "OK"):
        lines.append(f"- {status}: {counts.get(status, 0)}")

    lines.extend(["", "## Findings", ""])
    for row in rows:
        if row["status"] == "OK":
            continue
        lines.append(f"- **{row['status']}** `{row['section']}` / `{row['item']}`: {row['detail']}")

    if all(row["status"] == "OK" for row in rows):
        lines.append("- No warnings or failures.")

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(path)


def check_file(path: Path, section: str, item: str | None = None) -> None:
    label = item or str(path)
    if path.exists():
        add_check(section, label, "OK", str(path))
    else:
        add_check(section, label, "FAIL", f"missing: {path}")


def check_any_file(candidates: list[Path], section: str, item: str) -> None:
    existing = [path for path in candidates if path.exists()]
    if existing:
        add_check(section, item, "OK", "; ".join(str(path) for path in existing))
    else:
        add_check(section, item, "FAIL", "missing all candidates: " + "; ".join(str(path) for path in candidates))


def check_rollup_metric(path: Path, metric: str, expected: str | None = None) -> None:
    if not path.exists():
        add_check("result_metrics", f"{path}:{metric}", "FAIL", "missing file")
        return
    rows = read_csv(path)
    by_metric = {row.get("metric", ""): row.get("value", "") for row in rows}
    value = by_metric.get(metric)
    if value is None:
        add_check("result_metrics", f"{path}:{metric}", "FAIL", "metric not found")
        return
    if expected is not None and value != expected:
        add_check("result_metrics", f"{path}:{metric}", "WARN", f"value={value}, expected={expected}")
    else:
        add_check("result_metrics", f"{path}:{metric}", "OK", f"value={value}")


def check_component_ablation_rollup(path: Path, expected_cases: int = 12) -> None:
    if not path.exists():
        add_check("result_metrics", f"{path}:component_ablation_cases", "FAIL", "missing file")
        return
    rows = read_csv(path)
    if not rows:
        add_check("result_metrics", f"{path}:component_ablation_cases", "FAIL", "empty file")
        return

    if "metric" in rows[0] and "value" in rows[0]:
        by_metric = {row.get("metric", ""): row.get("value", "") for row in rows}
        value = by_metric.get("cases")
        if value == str(expected_cases):
            add_check("result_metrics", f"{path}:component_ablation_cases", "OK", f"value={value}")
        elif value is None:
            add_check("result_metrics", f"{path}:component_ablation_cases", "WARN", "metric/value rollup has no cases row")
        else:
            add_check("result_metrics", f"{path}:component_ablation_cases", "WARN", f"value={value}, expected={expected_cases}")
        return

    if "available_cases" in rows[0]:
        try:
            values = [int(float(row["available_cases"])) for row in rows if row.get("available_cases")]
        except ValueError:
            add_check("result_metrics", f"{path}:component_ablation_cases", "WARN", "available_cases is not numeric")
            return
        if values and max(values) >= expected_cases:
            add_check("result_metrics", f"{path}:component_ablation_cases", "OK", f"max_available_cases={max(values)}")
        else:
            add_check("result_metrics", f"{path}:component_ablation_cases", "WARN", f"available_cases={values}")
        return

    add_check("result_metrics", f"{path}:component_ablation_cases", "WARN", "unrecognized rollup format")


def check_numeric_bounds(path: Path, metric: str, low: float | None = None, high: float | None = None) -> None:
    if not path.exists():
        add_check("result_metrics", f"{path}:{metric}", "FAIL", "missing file")
        return
    rows = read_csv(path)
    by_metric = {row.get("metric", ""): row.get("value", "") for row in rows}
    value_text = by_metric.get(metric)
    if value_text is None:
        add_check("result_metrics", f"{path}:{metric}", "FAIL", "metric not found")
        return
    try:
        value = float(value_text)
    except ValueError:
        add_check("result_metrics", f"{path}:{metric}", "FAIL", f"not numeric: {value_text}")
        return
    if low is not None and value < low:
        add_check("result_metrics", f"{path}:{metric}", "WARN", f"value={value_text} below {low}")
    elif high is not None and value > high:
        add_check("result_metrics", f"{path}:{metric}", "WARN", f"value={value_text} above {high}")
    else:
        add_check("result_metrics", f"{path}:{metric}", "OK", f"value={value_text}")


def check_git_status(root: Path) -> None:
    try:
        result = subprocess.run(
            ["git", "status", "--short", "--branch"],
            cwd=root,
            check=False,
            text=True,
            capture_output=True,
        )
    except OSError as exc:
        add_check("git", "status", "WARN", f"could not run git: {exc}")
        return
    output = result.stdout.strip()
    if result.returncode != 0:
        add_check("git", "status", "WARN", result.stderr.strip() or "git status failed")
        return
    dirty_lines = [line for line in output.splitlines() if line and not line.startswith("## ")]
    if dirty_lines:
        add_check("git", "working_tree", "WARN", "uncommitted entries: " + " | ".join(dirty_lines[:12]))
    else:
        add_check("git", "working_tree", "OK", output.splitlines()[0] if output else "clean")


def check_docs_for_overclaims(root: Path) -> None:
    doc_paths = [root / "README.md"]
    doc_paths.extend(sorted((root / "docs").glob("*.md")) if (root / "docs").exists() else [])
    patterns = [
        re.compile(r"\bsignoff\b", re.IGNORECASE),
        re.compile(r"\bfull 3D\b", re.IGNORECASE),
        re.compile(r"\btrue 3D\b", re.IGNORECASE),
        re.compile(r"\balways improves\b", re.IGNORECASE),
        re.compile(r"\bguarantees timing\b", re.IGNORECASE),
        re.compile(r"\bproves real 3D\b", re.IGNORECASE),
        re.compile(r"\braw crossing superiority\b", re.IGNORECASE),
    ]
    safe_context = re.compile(
        r"not|does not|do not|no |without|proxy|limitation|limitations|doesn't|is not|"
        r"should not|avoid|out of scope|outside|future work|not currently|cannot claim|"
        r"does not claim|should be rejected|bad claim|not as",
        re.IGNORECASE,
    )
    flagged: list[str] = []
    for path in doc_paths:
        if not path.exists():
            continue
        lines = path.read_text(encoding="utf-8", errors="ignore").splitlines()
        for idx, line in enumerate(lines, start=1):
            start = max(0, idx - 3)
            end = min(len(lines), idx + 2)
            context = " ".join(lines[start:end])
            if any(pattern.search(line) for pattern in patterns) and not safe_context.search(context):
                flagged.append(f"{path.relative_to(root)}:{idx}:{line.strip()[:180]}")
    if flagged:
        add_check("docs", "possible_overclaims", "WARN", " | ".join(flagged[:20]))
    else:
        add_check("docs", "possible_overclaims", "OK", "no unsafe overclaim wording found")


def check_stale_files(root: Path) -> None:
    candidates: list[str] = []
    for path in root.glob("*.py"):
        name = path.name.lower()
        if name.startswith(("update_", "fix_")):
            candidates.append(str(path.relative_to(root)))
    for folder in ("evaluation", "partition", "scripts"):
        base = root / folder
        if not base.exists():
            continue
        for path in base.glob("*.py"):
            name = path.name.lower()
            if name.startswith(("update_", "fix_")):
                candidates.append(str(path.relative_to(root)))

    caches = []
    for path in root.rglob("__pycache__"):
        parts = set(path.parts)
        if ".git" not in parts:
            caches.append(str(path.relative_to(root)))

    if candidates:
        add_check("hygiene", "possible_one_off_scripts", "WARN", "; ".join(candidates[:20]))
    else:
        add_check("hygiene", "possible_one_off_scripts", "OK", "none found at top-level script locations")

    if caches:
        add_check("hygiene", "python_caches", "WARN", f"{len(caches)} __pycache__ directories found")
    else:
        add_check("hygiene", "python_caches", "OK", "none found")


def check_intermediate_outputs(root: Path) -> None:
    summary = root / "results" / "benchmark_summary"
    if not summary.exists():
        add_check("hygiene", "benchmark_summary_dir", "FAIL", "missing results/benchmark_summary")
        return
    intermediate_names = [
        "scenario_behavior_delta_summary.csv",
        "scenario_behavior_missing_inputs.csv",
        "scenario_behavior_pairwise_summary.csv",
        "scenario_behavior_semantic_gap_summary.csv",
        "scenario_behavior_semantic_tier_summary.csv",
        "scenario_behavior_unit_tier_summary.csv",
    ]
    existing = [name for name in intermediate_names if (summary / name).exists()]
    if existing:
        add_check("hygiene", "scenario_intermediate_tables", "WARN", "; ".join(existing))
    else:
        add_check("hygiene", "scenario_intermediate_tables", "OK", "compact scenario summaries only")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=Path("."))
    parser.add_argument("--output-dir", type=Path, default=Path("results/benchmark_summary"))
    args = parser.parse_args()

    root = args.repo_root.resolve()
    output_dir = args.output_dir if args.output_dir.is_absolute() else root / args.output_dir

    required_scripts = [
        "partition/partition_tritonpart_timing_regret_guarded_repair.py",
        "partition/partition_tritonpart_path_aware_guarded_repair.py",
        "evaluation/evaluate_path_aware_downstream_vertical_delay.py",
        "evaluation/analyze_scenario_behavior.py",
        "evaluation/summarize_scenario_behavior.py",
        "run_component_ablation.py",
        "run_path_aware_downstream_delay_sweep.py",
        "run_path_aware_downstream_pathcount_sweep.py",
        "plot_paper_results.py",
    ]
    for rel in required_scripts:
        check_file(root / rel, "required_scripts", rel)

    required_figures = [
        "results/figures/paper/fig5_1_timing_weighted_crossing.svg",
        "results/figures/paper/fig5_2_downstream_tns_degradation.svg",
        "results/figures/paper/fig5_3_component_ablation_timing_crossing.svg",
        "results/figures/paper/fig5_4_vertical_delay_sensitivity.svg",
        "results/figures/paper/fig5_4_ibex_path_budget_sensitivity.svg",
    ]
    for rel in required_figures:
        check_file(root / rel, "required_figures", rel)

    check_any_file(
        [
            root / "results/benchmark_summary/timing_regret_guarded_all_scenarios_summary.csv",
            root / "results/benchmark_summary/timing_regret_guarded_three_riscv_summary.csv",
            root / "results/benchmark_summary/timing_regret_guarded_four_core_summary.csv",
        ],
        "required_summaries",
        "5.1 timing-regret main summary",
    )

    required_summaries = [
        "results/benchmark_summary/path_aware_downstream_vertical_delay_rollup.csv",
        "results/benchmark_summary/path_aware_downstream_delay_sweep_rollup.csv",
        "results/benchmark_summary/path_aware_downstream_pathcount_sweep_rollup.csv",
        "results/benchmark_summary/path_aware_tradeoff_rollup.csv",
        "results/benchmark_summary/component_ablation_rollup.csv",
        "results/benchmark_summary/scenario_behavior_rollup.csv",
        "results/benchmark_summary/scenario_behavior_paper_summary.csv",
        "results/benchmark_summary/scenario_behavior_top_unit_changes.csv",
    ]
    for rel in required_summaries:
        check_file(root / rel, "required_summaries", rel)

    check_rollup_metric(root / "results/benchmark_summary/path_aware_downstream_vertical_delay_rollup.csv", "cases", "12")
    check_component_ablation_rollup(root / "results/benchmark_summary/component_ablation_rollup.csv")
    check_rollup_metric(root / "results/benchmark_summary/scenario_behavior_rollup.csv", "cases", "12")
    check_numeric_bounds(
        root / "results/benchmark_summary/path_aware_tradeoff_rollup.csv",
        "min_path_aware_instance_balance",
        low=0.9,
    )
    check_numeric_bounds(
        root / "results/benchmark_summary/path_aware_tradeoff_rollup.csv",
        "min_path_aware_weight_balance",
        low=0.9,
    )

    check_docs_for_overclaims(root)
    check_stale_files(root)
    check_intermediate_outputs(root)
    check_git_status(root)

    write_csv(output_dir / "paper_readiness_audit.csv", CHECKS)
    write_markdown(output_dir / "paper_readiness_audit.md", CHECKS)

    failures = sum(1 for row in CHECKS if row["status"] == "FAIL")
    warnings = sum(1 for row in CHECKS if row["status"] == "WARN")
    print(f"failures={failures} warnings={warnings} checks={len(CHECKS)}")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
