#!/usr/bin/env python3
"""Generate the reviewer-response baseline restoration report."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


def read_rows(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def read_metric_csv(path: Path) -> dict[str, str]:
    rows = read_rows(path)
    return {row.get("metric", ""): row.get("value", "") for row in rows if row.get("metric")}


def pick(rows: list[dict[str, str]], key: str, value: str) -> dict[str, str]:
    for row in rows:
        if row.get(key) == value:
            return row
    return {}


def md_table(rows: list[dict[str, str]], columns: list[str]) -> list[str]:
    if not rows:
        return ["_No rows found._"]
    out = ["| " + " | ".join(columns) + " |", "| " + " | ".join("---" for _ in columns) + " |"]
    for row in rows:
        out.append("| " + " | ".join(str(row.get(col, "")) for col in columns) + " |")
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("results/benchmark_summary/reviewer_baseline_restoration_report.md"),
    )
    args = parser.parse_args()
    root = args.root

    audit_path = root / "results/benchmark_summary/native_baseline_feasibility_audit.csv"
    scr1_analysis_path = root / "results/benchmark_summary/scr1_baseline_infeasibility_analysis.md"
    restoration_summary_path = root / "results/benchmark_summary/scr1_core_tuned_feasibility_restoration_summary.csv"
    restoration_moves_path = root / "results/benchmark_summary/scr1_core_tuned_feasibility_restoration_moves.csv"
    reviewer_rollup_path = root / "results/benchmark_summary/reviewer_scr1_restored_phase3_rollup.csv"
    reviewer_summary_path = root / "results/benchmark_summary/reviewer_scr1_restored_phase3_summary.csv"
    noop_path = root / "results/benchmark_summary/baseline_restoration_noop_check.csv"
    repo_state_path = root / "results/benchmark_summary/reviewer_baseline_restoration_repo_state.txt"

    audit_rows = read_rows(audit_path)
    restoration_rows = read_rows(restoration_summary_path)
    restoration_moves = read_rows(restoration_moves_path)
    reviewer_rollup = read_metric_csv(reviewer_rollup_path)
    reviewer_rows = read_rows(reviewer_summary_path)
    noop_rows = read_rows(noop_path)

    scr1_audit = pick(audit_rows, "design", "scr1_core_tuned")
    guarded_restoration = pick(restoration_rows, "policy", "guarded")

    lines: list[str] = [
        "# Reviewer Baseline Restoration Experiment",
        "",
        "This report is generated by `scripts/summarize_reviewer_baseline_restoration.py`.",
        "It documents the reviewer-response experiment for SCR1 native-baseline feasibility restoration.",
        "The experiment is separate from the frozen paper snapshots and does not retag or rewrite `paper-v1.1`.",
        "",
        "## 1. Repository State",
        "",
    ]
    if repo_state_path.exists():
        lines.extend(["```text", repo_state_path.read_text(encoding="utf-8").strip(), "```", ""])
    else:
        lines.extend(["_Repository state file not found._", ""])

    lines.extend(
        [
            "## 2. Native Baseline Feasibility Audit",
            "",
            *md_table(
                audit_rows,
                [
                    "design",
                    "native_timing_aware_completed",
                    "area_coverage_fraction",
                    "tier0_area_fraction",
                    "area_violation",
                    "reconstructed_area_pass",
                    "root_cause_status",
                ],
            ),
            "",
        ]
    )

    if scr1_audit:
        lines.extend(
            [
                "SCR1 is present with complete area coverage, but its imported native timing-aware baseline is slightly outside the strict reconstructed area-balance window.",
                f"The audited tier-0 area fraction is `{scr1_audit.get('tier0_area_fraction', '')}`, with violation `{scr1_audit.get('area_violation', '')}`.",
                "",
            ]
        )

    if scr1_analysis_path.exists():
        lines.extend(["### SCR1 Root-Cause Note", "", scr1_analysis_path.read_text(encoding="utf-8").strip(), ""])

    lines.extend(
        [
            "## 3. SCR1 Feasibility Restoration",
            "",
            *md_table(
                restoration_rows,
                [
                    "policy",
                    "status",
                    "baseline_tier0_area_fraction",
                    "final_tier0_area_fraction",
                    "area_violation_after",
                    "reconstructed_area_pass",
                    "baseline_crossing_nets",
                    "final_crossing_nets",
                    "cut_regret",
                    "baseline_P_avg_cut",
                    "final_P_avg_cut",
                    "baseline_P_wst_cut",
                    "final_P_wst_cut",
                    "moved_instances",
                    "guard_status",
                ],
            ),
            "",
        ]
    )
    if guarded_restoration:
        lines.extend(
            [
                "The guarded restoration succeeds with a small baseline repair:",
                f"`{guarded_restoration.get('moved_instances', '')}` moves, tier-0 area fraction `{guarded_restoration.get('final_tier0_area_fraction', '')}`, raw-cut regret `{guarded_restoration.get('cut_regret', '')}`, and guard status `{guarded_restoration.get('guard_status', '')}`.",
                "",
                "Restoration moves:",
                "",
                *md_table(
                    restoration_moves,
                    [
                        "policy",
                        "move_index",
                        "instance",
                        "architecture_unit",
                        "semantic_group",
                        "from_tier",
                        "to_tier",
                        "area",
                        "tier0_area_fraction_after",
                        "crossing_nets_after",
                        "reason",
                    ],
                ),
                "",
            ]
        )

    lines.extend(
        [
            "## 4. Post-Restoration SCR1 Phase-3 Results",
            "",
            "Rollup:",
            "",
            *md_table([{"metric": key, "value": value} for key, value in reviewer_rollup.items()], ["metric", "value"]),
            "",
            "Scenario-level summary:",
            "",
            *md_table(
                reviewer_rows,
                [
                    "scenario",
                    "status",
                    "on_accepted_moves",
                    "off_accepted_moves",
                    "native_crossing_nets",
                    "on_crossing_nets",
                    "off_crossing_nets",
                    "on_timing_weighted_reduction_vs_native",
                    "on_structural_reduction_vs_native",
                    "on_structural_reduction_vs_off",
                    "architecture_on_better_structural_than_off",
                    "max_on_P_avg_cut_regret",
                ],
            ),
            "",
            "Interpretation: after baseline restoration, SCR1 can be processed under the strict area and timing-path guards. However, this run remains mixed evidence: raw crossing increases relative to the original native baseline, timing-weighted crossing is unchanged, and architecture-ON is better than OFF structurally in two of three scenarios but not better than native overall.",
            "",
            "## 5. No-Op Regression on Already Feasible Baselines",
            "",
            *md_table(
                noop_rows,
                [
                    "design",
                    "status",
                    "noop_pass",
                    "tier_maps_identical",
                    "move_rows",
                    "moved_instances",
                    "baseline_tier0_area_fraction",
                    "final_tier0_area_fraction",
                    "baseline_crossing_nets",
                    "final_crossing_nets",
                    "cut_regret",
                ],
            ),
            "",
            "PicoRV32 and riscv32i are already feasible under the reconstructed area window; the restoration mechanism leaves their tier maps unchanged.",
            "",
            "## 6. Conclusion",
            "",
            "This experiment supports using SCR1 as reviewer-response or supplementary boundary evidence. The native SCR1 assignment is only marginally outside the strict reconstructed area window, a guarded five-move restoration brings it inside the window, and subsequent Phase-3 runs respect the path guards. The outcome does not turn SCR1 into a strong primary architecture-context success case, so the frozen paper tables should remain unchanged unless the manuscript explicitly adds this as supplemental analysis.",
            "",
            "## 7. Key Output Files",
            "",
            "- `results/benchmark_summary/native_baseline_feasibility_audit.csv`",
            "- `results/benchmark_summary/scr1_baseline_infeasibility_analysis.md`",
            "- `results/benchmark_summary/scr1_core_tuned_feasibility_restoration_summary.csv`",
            "- `results/benchmark_summary/scr1_core_tuned_feasibility_restoration_moves.csv`",
            "- `results/benchmark_summary/reviewer_scr1_restored_phase3_rollup.csv`",
            "- `results/benchmark_summary/reviewer_scr1_restored_phase3_summary.csv`",
            "- `results/benchmark_summary/baseline_restoration_noop_check.csv`",
            "",
        ]
    )

    output = root / args.output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
